### ISSUE TITLE
关于NEUQ-OJ在判题上的问题

### ISSUE THREAD

**Issue by jks15satoshi** [ouxu/NEUQ-OJ#12]
我在回答NEUQ-OJ上提供的编程问题时，发现自己的答案明明**只是格式上与网上提供的答案不同**，其他不论是标识符命名还是语句的位置都与答案完全一致，系统却判我的回答为“答案错误”，而网上的答案则通过了。
我想请问一下这是为什么？编程语言不应该是格式自由的吗？为什么会因为格式问题判错？

**Comment by ouxu** [comment]
贴代码吧
